
# Logging config
logging:
  config: "src/main/resources/logback-spring.xml"

# web port
server:
  port: 9090

# console
spring:
  output:
    ansi:
      enabled: always

# files
file:
  reader:
    key: fileReader
  name:
    key: fileName
  path:
    input: batch-test.csv
    read: file:${user.dir}/../file/*.csv
    readSingle: ${user.dir}/../file/batch-test.csv
    success: ${user.dir}/../file/Success/
    error: ${user.dir}/../file/Error/