
# Logging config
logging:
  config: "src/main/resources/logback-spring.xml"

# web port
server:
  port: 9090

# console
spring:
  output:
    ansi:
      enabled: always

# Datasource
  profile: dev-local
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/prod_smart_cms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  batch:
    initialize-schema: always
  profiles:
    include:
      - sql
  data:
    jpa:
      repositories:
        enabled: true
      hibernate:
        ddl-auto: none

# files
file:
  reader:
    key: fileReader
  name:
    key: fileName
  path:
    input: batch-test.csv
    read: file:${user.dir}/../file/*.csv
    readSingle: ${user.dir}/../file/batch-test.csv
    success: ${user.dir}/../file/Success/
    error: ${user.dir}/../file/Error/